### ISSUE TITLE
Scroll speed on touch devices

### ISSUE THREAD

**Issue by rarkins** [gopatrik/space.js#9]
On desktop, demo 1 seems a little fast, but on an iPhone (Safari) it's super fast and you have to concentrate to not blow past the content. I assume speed can be controlled, but is there any way to fix this (perceived) disparity between desktop and mobile scroll speeds? I wouldn't want to slow down Desktop so much that the effect is diminished.

**Comment by gopatrik** [comment]
Hi!

I've been struggling with this also; I think the problem is pixel density and device-size/orientation. I'll try to think of some clever formula for speed.

You are most welcome to play with this value in the meantime; ```0.3``` means that currently mobile runs about three times faster than desktop.

 ``~line 170:`var touchScreenCompensation = (isMobile() ? 0.3 : 1);```

Cheers!
